### ISSUE TITLE
MalformedSchemaException when using multiple schemas

### ISSUE THREAD

**Issue by cakrt** [ssilverman/snowy-json#3]
Hi, it seems that snow is having a problem when parsing a schema that references another schema via **$ref**. Please see the attached files.

stage-league-table.schema.json: [https://pastebin.com/WmQrJGjy](url)
common.schema.json: [https://pastebin.com/ae0mcNEF](url)

Both files are in the same directory. CoreRef.apply() fails with an exception:
`Exception in thread "main" com.qindesign.json.schema.MalformedSchemaException: file:/C:/Work/java/LiveScore-DATA/src/main/resources/schemas/stage-league-table.schema.json#/stageLeagueTable/properties/categoryId/$ref: unknown reference: common.schema.json#/providerString
	at com.qindesign.json.schema.ValidatorContext.schemaError(ValidatorContext.java:908)
	at com.qindesign.json.schema.ValidatorContext.schemaError(ValidatorContext.java:931)
	at com.qindesign.json.schema.keywords.CoreRef.apply(CoreRef.java:108)
	at com.qindesign.json.schema.ValidatorContext.applyKeyword(ValidatorContext.java:1196)
	at com.qindesign.json.schema.ValidatorContext.apply(ValidatorContext.java:1162)
	at com.qindesign.json.schema.keywords.Properties.apply(Properties.java:70)
	at com.qindesign.json.schema.ValidatorContext.applyKeyword(ValidatorContext.java:1196)
	at com.qindesign.json.schema.ValidatorContext.apply(ValidatorContext.java:1162)
	at com.qindesign.json.schema.keywords.CoreRef.apply(CoreRef.java:116)
	at com.qindesign.json.schema.ValidatorContext.applyKeyword(ValidatorContext.java:1196)
	at com.qindesign.json.schema.ValidatorContext.apply(ValidatorContext.java:1162)
	at com.qindesign.json.schema.Validator.validate(Validator.java:323)
	at com.qindesign.json.schema.Main.main(Main.java:123)
`

It seems than Validator.scanIds() does not find the reference to common.schema.json.

**Comment by cakrt** [comment]
The schemas are not complete. But I think they should pass the validation.

**Comment by ssilverman** [comment]
Do you have an instance for me to try? CoreRef isn't followed until executed. What I'd like to do is get it working and then show you what I did to get it working.

An explanation: The core of the issue is that by default, the validator doesn't know about any external reference URIs, so it doesn't know how to retrieve whatever it is the URI is pointing to. Note that "file location", a URL, is not the same thing as an ID, a URI. URIs technically provide no way to actually retrieve a resource, even though they look like URLs; recall that URLs are a "retrievable resource location" but URIs are just a simple ID. They may look like URLs but they're not.

In this case, it sees the "common.schema.json" URI but doesn't know that this really means "Load the file 'common.schema.json' from the current working directory."

You either have to add to the list of known IDs or try turning on the AUTO_RESOLVE option (see `Main.main`). This option enables some guessing about how the validator should translate URIs into retrievable URLs.

**Comment by ssilverman** [comment]
I'll also note that "stageLeagueTable", "leagueTables", and "leagueTable" should be underneath "definitions" (Draft 07) or "$defs" (Draft 2019-09). Same for all other schemas in the other schema file, for example "sportId".

**Comment by cakrt** [comment]
Hi ssilverman, thanks a lot for getting back to me. I turned the AUTO_RESOLVE option on before my first post here, I figured that out myself.

Previously I used this method of referencing in another project, we used REST assured for testing some JSON output, it could find the references but REST assured only supports JSON schemas up to draft 4. And want to use the features introduced in the more recent versions of JSON schema and I've found snowy-json.

As per your recommendation, I moved some definitions under "definitions".

I included a zip file with the schemas, stage-league-table.schema.json is the main schema, common.schema.json contains some extra definitions. Test.json is the testing data. Note that test.json may not validate against the schema, this is not a problem. The schemas are being developed and I want to use snowy-json for testing. But at this point the schema does not even load.
[json.zip](https://github.com/ssilverman/snowy-json/files/4856632/json.zip)

**Comment by ssilverman** [comment]
Thanks for the examples. I found the issue and will fix it when I have a chance.

**Comment by cakrt** [comment]
Thanks a lot!

**Comment by ssilverman** [comment]
Just a note that you can get this working until I push the fix by adding to the "known URLs". (Let me know if you need some assistance with that.) An example is in the `Test` program, where it needs to know where to find some references.

**Comment by ssilverman** [comment]
@cakrt See if the latest push fixes the issue for you. I was able to see it run successfully on my end.

**Comment by cakrt** [comment]
Yes, it seems to work now. Thank you. Have a nice day.
