### ISSUE TITLE
Duplicate root schemas issue

### ISSUE THREAD

**Issue by marcocamacho** [ssilverman/snowy-json#9]
Hi,

In the below example I have two different files for an Organization and Person schema in the same directory. I want to be able to validate an Organization and a Person independently (so none of them are contained into the other's definitions annotation) though they both have a reference to each other. 

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/schemas/organization.json",
    ...
    "employee": {
            "type": "array",
            "items": {
                    { "$ref": "http://example.com/schemas/person.json" }
            }
        }
```

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/schemas/person.json",
    ...
        "worksFor":  { "$ref": "http://example.com/schemas/organization.json" }       
```

I am taking the Person schema as the `Validator`s base schema and the Organization as `knownURL`:

```
            personSchema = JSON.parse(personSchemaStream);
            ...
            pknownURLs = Map.of(
                    new URI(new java.net.URI("http://example.com/schemas/organization.json")),
                    new URL(new File(organizationSchemaFile).toURI().toString()),

           ....
           personValidator = new Validator(personSchema, schemaID, null, pknownURLs, opts);
```

What I get is an `java.lang.IllegalArgumentException:  Duplicate root ID: file:/.../test-classes/: http://example.com/schemas/organization.json`

Do you have any idea why that is? It seems to me that it should be possible to ref the other file schema via `id` even though is not defined in the `definitions` section, am I missing something?

**Comment by ssilverman** [comment]
Thanks for the report. Can you provide a complete example for me? I can’t debug it otherwise. I have to see the whole schemas and program. (I prefer a cut-down version that demonstrates the problem.)

**Comment by ssilverman** [comment]
I don't seem to see the error. Some questions and comments.
1. Which version of the software are you using? The latest is 0.15.0.
2. What are you passing for `schemaID`?
3. I have a minimal program that shows the example working, below.
4. You need to put any referenced schemas into `"definitions"` (for Draft 7). While that will affect validation, it won't affect parsing and processing, that's why I didn't fix it below; I just want to test what you're seeing.

The program:
```java
import com.google.gson.JsonElement;
import com.qindesign.json.schema.net.URI;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Map;

public class Debug {
  public static void main(String[] args) throws IOException, MalformedSchemaException {
    File schemaFile = new File("tests/person.json");
    JsonElement schema = JSON.parse(schemaFile);
    Map<URI, URL> knownURLs =
        Map.of(URI.parseUnchecked("http://example.com/schemas/organization.json"),
               new File("tests/organization.json").toURI().toURL());

    Validator validator = new Validator(schema, new URI(schemaFile.toURI()), null, knownURLs, null);
  }
}
```

tests/person.json:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/schemas/person.json",
  "worksFor": {
    "$ref": "http://example.com/schemas/organization.json"
  }
}
```

tests/organization.json (there's an error in your JSON above: an object can't directly contain another object; I've fixed that (`items`)):
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/schemas/organization.json",
  "employee": {
    "type": "array",
    "items": {
      "$ref": "http://example.com/schemas/person.json"
    }
  }
}
```

**Comment by marcocamacho** [comment]
Thanks for the response. I was using version 0.14 (I have upgraded). The configuration you described is something I had tried before and it works if you validate the instance against the main schema (`person-instance.json` vs `person.json`), but if you try against an organization instance it won't work (the library will try to validate `organization-instance.json` vs `person.json`, the main schema). In my schema, I have the following for the organization and person schema, correspondingly:

```
    "properties": {
        "@type": { "const": "Organization" },
```
```
    "properties": {
        "@type": { "const": "Person" },
```

The error I get is `required properties not found: "name", schema didn't validate, invalid properties: "@type"; "const" didn't validate; ; `

Let me know if you need a sample, I guess it won't be hard to recreate since you already have recreated what matters.

**Comment by ssilverman** [comment]
Do you think you’re still seeing a bug in Snow or do you think this is just a schema design issue? Happy to have a look if you can give me a complete example.

From your description it sounds like either you’re trying to validate an instance against the wrong schema, or that the validator is correctly rejecting an incorrect instance.

**Comment by marcocamacho** [comment]
I think at this point the original issue is solved, but just turned into a question to whether the same validator can be used against multiple schemas or would it take an instance per schema, that is, a validator for Person with Organization as known URL, and a validator for Organization with Person as known URL. Will try to provide an example tonight

**Comment by ssilverman** [comment]
A Validator instance can only be used with one schema (but multiple instances to be validated). Of course, the schema can reference other schemas. When I say “one schema”, this really means “one entry point schema, possibly pointing to others.”

**Comment by marcocamacho** [comment]
That answers my question. I don't know how other validators work, but it seems like a good feature for the validator to be able validate anything known. I actually thought that the `knownIDs` parameter in the `validate` method was for that purpose, which led me to the original `Duplicate root schema` issue.

Thanks for answering about this issue.

**Comment by ssilverman** [comment]
It can validate anything. Just think of a `Validator` as a representation of a schema. Eg. “new Schema()”. Other validators that use the same object for multiple schemas just means you need to pass more parameters when you validate. I believe the way I’m doing it simplifies the API.

This is a common design approach, where “one instance” models “one thing”.

I’ll clarify this in the documentation. Thanks for bringing it up.

**Comment by marcocamacho** [comment]
I see. What's the purpose of the knownIDs parameter then?

**Comment by ssilverman** [comment]
One of the concepts in JSON schemas is “IDs”. Per the URI spec, things can be named with URIs, otherwise known as “IDs”. They can be referenced or simply assigned to some JSON. The `knownIDs` parameter maps IDs to some JSON. Similarly, the `knownURLs` parameter maps IDs to retrievable content.

Now, if a schema needs to reference an ID, it needs to know what other JSON is mapped to that ID. For example, see the docs for “$ref” or “$id”. These reference and assign an ID to, respectively, some other JSON. The validator needs to know how to access that JSON. It can either use something pre-parsed (`knownIDs`) or use something that can be retrieved (`knownURLs`).

In summary, a single schema may potentially need to access other JSON, either internal or external. That’s what those parameters provide, the means for that access.

URIs (IDs) by themselves are just a name. They provide no way to access the thing they name, even if they _look like_ URLs. They’re not URLs. Thus, we need a way to map URIs to the thing they name. Note: one of the things the AUTO_RESOLVE option attempts is to access an unknown URI (i.e. not in the `known` parameters) _as if_ it were a URL. Incidentally, that’s why so many URIs use “http” as the scheme, so that, if treated as a URL, it can be accessed.

The validator is smart enough to know about any internal IDs in a schema. Those two parameters inform the validator how to access anything external to the schema.

**Comment by ssilverman** [comment]
Another thought. Think of the Validator instance as “one schema plus everything it needs to access external URIs (otherwise known as IDs).”

Note that the required “base URI” parameter is the fallback URI if the schema itself doesn’t have a declared ID. The value is often the same as the URL used to retrieve the schema (eg. something with a “file:” or “http:” scheme).

**Comment by marcocamacho** [comment]
Thanks for the detailed explanation. Given that the validator for schema A knows how to access external URIs/known-IDs (including schema B), wouldn't the validator has enough information to validate schema B itself? The validator could look at the ID of the schema, if it happens to be schema B and not A, lookup B from the list of known ID's and validate accordingly. That approach is apparently possible and it does not seem to created more configuration overhead, but just more internal logic to the validator, although I may be missing something or that approach would deviate from the standard.

I am thinking in the case where one could have multiple schema instances and they are interrelated but at the same time they may need to validate independently. I am thinking in the case of the FHIR standard, where an Encounter (doctor visit) is linked to a Patient and there are MedicationRequest's, etc. associated. Those schema instances might be stored and validated independently, and one would need to have as many validator instances as schemas.

**Comment by ssilverman** [comment]
Yes, all the information is there, but you’d still need to tell the validator which schema is being used to validate an instance.

I’m hearing the suggestion that, when creating a validator, instead of giving it one schema plus its references, that you give it all known schemas (via parsed JsonElements or URLs), and then when validating an instance, instead of “validator.validate(instance)”, you’re saying do instead “validator.validate(schemaID, instance)”.

Does that sound right? i.e. The only API difference is that the validator isn’t keyed to only one schema. Instead of passing the schema ID in the constructor, it’s passed to the validate method.

**Comment by marcocamacho** [comment]
Yes, `validator.validate(schemaID, instance)` would work well. One step further would be to do `validator.validate(instance)` and let the validator pick up the schema if the instance has an `id` (that would be my use case)

**Comment by ssilverman** [comment]
> let the validator pick up the schema if the instance has an id

This is the thing. There isn't a mechanism for an instance to say which schema it needs to validate against. There's no standard way, for example, to have some "validating-schema-id" property. Only the user of a validating library knows which schema to apply to an instance.

**Comment by ssilverman** [comment]
@marcocamacho second point/question: why do you prefer to have the schema ID passed to the “validate” method rather than the constructor? My preference, even if there’s a “SchemaBank”, is to return some object instance, say via some “bank.getSchema(ID)” call, that refers to only one schema, and then there’ll still be a “validate(instance)” call.

Recall that, unless passed in somewhere, the validator can’t know which schema to apply to an instance.

**Comment by marcocamacho** [comment]
>  There isn't a mechanism for an instance to say which schema it needs to validate against. There's no standard way, for example, to have some "validating-schema-id" property. 

What would happen if the validator did something like this:
- `var validator = new Validator(schema, knownURLs ...)`
- `validator.validate(instance)`
- then `instance` is already a `JsonElement`, the validator could look at whether the `id` property is defined, if so, look for the corresponding schema from schemaID and knownURLs' URI keys. Then there are these possibilities:
  - no instance `id` prop, continue with current flow
  - instance `id` prop match a `knownURL` URI, then validator would look up knownURL schema (as it was a ref) and validate against it.
  - instance `'id` prop doesn't match, then use `schema` as default to validate against.
  - (optional) instance `id` prop match `schemaID`, then do validation again `schema` 

Example:
```
var schemaA = JSON.parse(new File(schemaA));
var validator = new Validator(schemaA, Map.of( 'http://example.com/schemaB', 'file://schemaB', 
        ... 'http://example.com/schemaN', 'file://schemaN' )  ...)  // <-- simplified URI and URL for brevity
validator.validate(instanceA)
validator.validate(instanceB)
...
validator.validate(instanceN)
```

**Comment by ssilverman** [comment]
That’s a customization that belongs in your own code, not in the API. Others may have a different approach, and there’s also no JSON specification that defines this. You could write your own simple wrapper here.

I’m also not seeing the point of passing in the schema if it’s going to be overridden by the instance. That’s why its choice is separate and should be defined by user code, not the API.

What if “id” is used for a different purpose by someone else? Your suggested behaviour may not be desired, so now you’d have to set more customization options. It gets too messy. This is another reason why this doesn’t belong in the API.

Keep in mind that the purpose of an API is to be as broadly useful as possible. It needs enough flexibility for everyone to use, but also provide the means to do custom things a user may need. You’re describing a “use of an API”.

“Validator.validate(instance.get(“id”), instance)” (Plus whatever logic is necessary for the case where there’s no “id” element, or whatever other logic is needed to find a schema.)

I appreciate your perspectives and for the opportunity to think more about the API design.

**Comment by marcocamacho** [comment]
Gotcha, I see your perspective. My concern was not merely about the logic, but about the fact that the wrapper would need N validator instances for N schemas. In my perspective, one validator instance could validate whatever schema is known.

> I’m also not seeing the point of passing in the schema if it’s going to be overridden by the instance.

Agreed, didn't want to remove it so it wouldn't look too disruptive.

Good thing is there is a solution to my problem, and I appreciate a lot you taking the time to both write the API and answer to this now long thread. Good luck and until next issue (hopefully there will be none :D )

**Comment by ssilverman** [comment]
My pleasure. Even if I disagree, it still gives me the opportunity to think of things in a different light, a perspective from a user of the software, which is important.

In the Java world, having lots of objects isn’t really a problem. The JVMs are designed to handle them well. Having N validator instances for N schemas isn’t really a heavyweight endeavour. Now, maybe the names are confusing; I’ll think about it more.
